language: java

jdk:
  - openjdk8

script:
  - ./gradlew assemble
  - ./gradlew test

deploy:
  provider: bintray
  file: ./descriptor.json
  user: vincent-paing
  key: $BINTRAY_API_KEY
  skip_cleanup: true # to upload artifacts created during the build
