language: java

jdk:
  - openjdk8

stages:
- compile
- test
- name: deploy
  if: branch = master

jobs:
  include:
    - stage: compile
      script: ./gradlew assemble
    - stage: test
      script: ./gradlew test
    - stage: deploy
      script: ./gradlew bintrayUpload


